import type { OriginalLanguage, SharePlatform } from "@shared/types";

export type UiLanguage = OriginalLanguage;

const platformLabels: Record<UiLanguage, Record<SharePlatform, string>> = {
  zh: {
    wechat: "微信",
    xiaohongshu: "小红书",
    weibo: "微博",
    douyin: "抖音",
    copy: "复制",
  },
  en: {
    wechat: "WeChat",
    xiaohongshu: "RedNote",
    weibo: "Weibo",
    douyin: "Douyin",
    copy: "Copy",
  },
};

export const getPlatformLabel = (language: UiLanguage, platform: SharePlatform) => platformLabels[language][platform];

export const getUiCopy = (language: UiLanguage) => {
  if (language === "en") {
    return {
      appLoading: "Gathering today's poem cards…",
      configTitle: "Welcome to Daily Poem Card",
      configBody: "Before the first launch, configure your preferred LLM. Poet dialogue, critic review, and poetic debate all run through that model.",
      configSave: "Save and Enter",
      configHint: "Any OpenAI-compatible API is supported, including Kimi, OpenAI, and DeepSeek. The runtime config will be written next to the app as llm.config.json.",
      fillLlm: "Please complete the LLM configuration first.",
      configSaved: "LLM config saved. Loading today's deck…",
      eyebrow: "Daily Poem Stack",
      todayTitle: "Today's Selection",
      languageSwitchAria: "Switch application language",
      openExportDir: "Open Export Folder",
      browserPreview: "Browser Preview",
      poetAtlas: "Poet Atlas",
      featuredReturn: "Back to Today's Selection",
      emptyTitle: "You've reached the end of today's library",
      emptyBody: "The current library is exhausted. Add more poems through poems.library.json, or clear the local reading history and generate a new deck.",
      atlasTitle: "Poet Atlas",
      unlockedPoets: "Unlocked Poets",
      noUnlockedPoets: "No distilled poet persona yet. Browse poems and enter Poet Dialogue to begin distillation.",
      collected: (count: number) => `Collected ${count}`,
      abstractedMs: (value: number) => `Abstracted ${value}ms`,
      calibratedMs: (value: number) => `Calibrated ${value}ms`,
      totalMs: (value: number) => `Total ${value}ms`,
      metricsTotal: (value: number) => `Total ${value}ms`,
      metricsDistill: (value: number) => `Distill ${value}ms`,
      metricsReply: (value: number) => `Reply ${value}ms`,
      metricsWrap: (parts: string[]) => ` (${parts.join(", ")})`,
      sourceCached: "Cached",
      sourceRecalibrated: "Recalibrated",
      sourceDistilled: "Redistilled",
      sourceBackground: "Background distillation",
      sourceFailed: "Distillation failed",
      freshnessCurrent: "Current",
      freshnessUpdated: "Source Updated",
      languageLabel: "Language",
      thinkingLabel: "Thinking",
      valuesLabel: "Values",
      calibrationLabel: "Calibration",
      dialogueGuardrails: "Dialogue Guardrails",
      sourceWorks: "Source Works",
      debateTitle: "Poetic Debate",
      choosePoetA: "Choose Poet A",
      choosePoetB: "Choose Poet B",
      selectedA: (name: string) => `${name} (chosen as A)`,
      selectedB: (name: string) => `${name} (chosen as B)`,
      debatePlaceholder: "Enter a topic, e.g. Should one seize delight while it lasts?",
      debateGenerate: "Generate Debate",
      debateGenerating: "Generating…",
      debateTopic: "Topic",
      debateSummary: "Summary",
      noDebateResult: "No debate result was returned by the agent.",
      previewDebateView: (speaker: string) => `[Preview] Simulated view from ${speaker}.`,
      previewDebateSummary: "Browser preview mode: configure llm.config.json on desktop to experience the full poetic debate.",
      soulResonance: "Soul Resonance",
      poetDialogue: "Poet Dialogue",
      feynmanExplain: "Feynman Lens",
      mungerReview: "Munger Review",
      chatPlaceholderWithAuthor: (author: string) => `Say something to ${author}…`,
      chatPlaceholderNoPoem: "Pick a poem before starting the dialogue…",
      feynmanPlaceholder: "Let Feynman unfold this poem…",
      mungerPlaceholder: "Let Munger examine this poem…",
      resonancePlaceholder: "Enter a mood, a season, a fragment, or a line…",
      sendMessage: "Send message",
      submit: "Submit",
      cardsReady: "Today's card stack is ready.",
      libraryFinished: "No unread poem remains in the current library.",
      syncDeckFailed: (msg: string) => `Deck sync failed: ${msg}`,
      previewStatus: "Browser preview mode: flipping and layout are available, while save and share stay desktop-only.",
      loadingFailed: (msg: string) => `Loading failed: ${msg}`,
      motionRuntimeUnavailable: "Built-in motion rendering is unavailable in this installation. The app will fall back to static artwork, and animated export will stay disabled until the runtime is restored.",
      animatedExportUnavailable: "Animated export is unavailable because the motion runtime is not ready.",
      bridgeReload: (feature: string) => `${feature} bridge is not loaded in this window. Fully close the dev window and run npm run dev again.`,
      resonanceSaved: (prompt: string) => `Your resonance has been noted: ${prompt}`,
      resonanceReady: "Soul resonance captured. Keep writing to build a living note around the poem.",
      resonanceEcho: (title: string, prompt: string, anchor: string) => `This feeling already leans toward the atmosphere of ${title}: ${prompt}. Read it once beside “${anchor}”, then add one more line closer to your present mood.`,
      choosePoetsAndTopic: "Choose two poets and enter a debate topic.",
      chooseDifferentPoets: "Choose two different poets for the debate.",
      debateReady: "Poetic debate is ready.",
      debateGeneratingStatus: "Generating poetic debate…",
      previewDebateGenerated: "Browser preview: a simulated debate has been prepared.",
      saveText: "Save Text",
      saveRichCard: "Save Animated Card",
      preparingExportMotion: "Rendering a balanced export animation for this card…",
      featuredChip: "Featured Today",
      generatingBackground: "Rendering a motion background attuned to the poem…",
      hoverToReadFull: "Hover to read the full text…",
      authorDisabledReason: "This anonymous poet cannot yet be distilled into a dialogue persona.",
      distillingPersona: (author: string) => `Distilling ${author}'s persona…`,
      previewDistilled: "Browser preview: simulated distillation finished.",
      turningToPoem: (title: string) => `Turning toward ${title}…`,
      poemFaceUp: (title: string) => `${title} is now face up.`,
      reviewDefaultPrompt: "Please review this poem.",
      previewReply: (author: string) => `[Browser Preview]\nThis is a simulated reply from ${author}. Configure llm.config.json on desktop to speak with the real distilled persona.`,
      previewCritic: (critic: string) => `[Browser Preview]\nThis is a simulated review from ${critic}. Configure llm.config.json on desktop to unlock the full critic mode.`,
      bridgeMissingPrefix: "[Bridge Missing]",
      distillFailedPrefix: "[Distillation Failed]",
      askAuthorIntro: (author: string, meta: string, title: string) => `I am ${author}, ${meta}. You are reading my ${title}. What stirred in you?`,
      feynmanIntro: (title: string) => `I'm Feynman. Let me unpack ${title} in the clearest possible language. Where shall we begin?`,
      mungerIntro: (title: string) => `I'm Munger. Let me examine ${title} through a latticework of mental models. Press send to begin.`,
    };
  }

  return {
    appLoading: "正在载入诗歌卡片…",
    configTitle: "欢迎使用 Daily Poem Card",
    configBody: "首次使用需要先配置你的大语言模型（LLM）。所有 AI 功能，包括诗人对话、评论家点评与诗坛交锋，都将经由该模型运行。",
    configSave: "保存并进入应用",
    configHint: "支持任何 OpenAI-compatible API（Kimi、OpenAI、DeepSeek 等）。运行时配置会写在应用目录旁边的 llm.config.json。",
    fillLlm: "请填写完整的 LLM 配置信息。",
    configSaved: "LLM 配置已保存，正在加载今日卡组…",
    eyebrow: "Daily Poem Stack",
    todayTitle: "今日推荐",
    languageSwitchAria: "切换应用语言",
    openExportDir: "打开导出目录",
    browserPreview: "浏览器预览",
    poetAtlas: "诗人图鉴",
    featuredReturn: "回到当日推荐",
    emptyTitle: "今天的诗库已经走完了",
    emptyBody: "你已经看完当前诗库。可以继续补充 poems.library.json，或者清空本地阅读记录重新生成推荐。",
    atlasTitle: "诗人图鉴",
    unlockedPoets: "已解锁诗人",
    noUnlockedPoets: "暂无已解锁的诗人 persona。浏览诗歌并进入“与作者对话”模式即可自动炼化。",
    collected: (count: number) => `采集 ${count} 首`,
    abstractedMs: (value: number) => `抽象 ${value}ms`,
    calibratedMs: (value: number) => `校准 ${value}ms`,
    totalMs: (value: number) => `总计 ${value}ms`,
    metricsTotal: (value: number) => `总耗时 ${value}ms`,
    metricsDistill: (value: number) => `炼化 ${value}ms`,
    metricsReply: (value: number) => `回复 ${value}ms`,
    metricsWrap: (parts: string[]) => `（${parts.join("，")}）`,
    sourceCached: "命中缓存",
    sourceRecalibrated: "仅重校准",
    sourceDistilled: "已重炼化",
    sourceBackground: "后台炼化中",
    sourceFailed: "炼化失败",
    freshnessCurrent: "当前",
    freshnessUpdated: "素材已变",
    languageLabel: "语言",
    thinkingLabel: "思维",
    valuesLabel: "价值",
    calibrationLabel: "校准",
    dialogueGuardrails: "对话约束",
    sourceWorks: "采集作品",
    debateTitle: "诗坛交锋",
    choosePoetA: "选择诗人 A",
    choosePoetB: "选择诗人 B",
    selectedA: (name: string) => `${name}（已选 A）`,
    selectedB: (name: string) => `${name}（已选 B）`,
    debatePlaceholder: "输入辩论主题，例如：人生得意须尽欢？",
    debateGenerate: "生成交锋",
    debateGenerating: "生成中…",
    debateTopic: "主题",
    debateSummary: "总结",
    noDebateResult: "未收到智能体交锋结果。",
    previewDebateView: (speaker: string) => `【浏览器预览】${speaker} 的模拟观点。`,
    previewDebateSummary: "浏览器预览模式：请在桌面端配置 llm.config.json 后体验真正的诗坛交锋。",
    soulResonance: "灵魂共鸣",
    poetDialogue: "与作者对话",
    feynmanExplain: "费曼讲解",
    mungerReview: "芒格点评",
    chatPlaceholderWithAuthor: (author: string) => `对 ${author} 说点什么…`,
    chatPlaceholderNoPoem: "选择一首诗后开始对话…",
    feynmanPlaceholder: "让费曼讲解这首诗（点击发送即可）…",
    mungerPlaceholder: "让芒格点评这首诗（点击发送即可）…",
    resonancePlaceholder: "输入你想要的意境、主题、季节或一句诗…",
    sendMessage: "发送消息",
    submit: "提交",
    cardsReady: "今日推荐卡片已经就位。",
    libraryFinished: "诗库已全部浏览完毕，可以稍后补充新诗歌。",
    syncDeckFailed: (msg: string) => `同步卡组失败：${msg}`,
    previewStatus: "当前为浏览器预览模式：翻牌与布局可预览，保存和分享仅桌面端可用。",
    loadingFailed: (msg: string) => `加载失败：${msg}`,
    motionRuntimeUnavailable: "当前安装包内置的动态渲染运行时不可用。应用会回退为静态封面展示，动图导出在运行时恢复前不可用。",
    animatedExportUnavailable: "当前动态渲染运行时未就绪，无法导出动图卡片。",
    bridgeReload: (feature: string) => `${feature}桥接尚未加载到当前窗口。请完整关闭当前 dev 窗口后重新执行 npm run dev。`,
    resonanceSaved: (prompt: string) => `已记录你的灵感：${prompt}`,
    resonanceReady: "灵魂共鸣已生成。继续输入，可以累积你的意境笔记。",
    resonanceEcho: (title: string, prompt: string, anchor: string) => `这句灵感已经贴近《${title}》的气息：${prompt}。不妨把它和“${anchor}”并读，再补上一句更贴近你此刻心境的话。`,
    choosePoetsAndTopic: "请选择两位诗人并输入辩论主题。",
    chooseDifferentPoets: "请选择两位不同的诗人进行交锋。",
    debateReady: "诗坛交锋已生成。",
    debateGeneratingStatus: "正在生成诗坛交锋…",
    previewDebateGenerated: "浏览器预览：模拟交锋已生成。",
    saveText: "保存文本",
    saveRichCard: "保存动图卡片",
    preparingExportMotion: "正在为这张卡片渲染导出用的平衡质量动画…",
    featuredChip: "当日推荐",
    generatingBackground: "正在生成与诗意相关的动态背景…",
    hoverToReadFull: "悬停查看全文…",
    authorDisabledReason: "当前这位匿名诗人尚不能稳定炼化为可对话 persona。",
    distillingPersona: (author: string) => `正在炼化 ${author} 的 persona…`,
    previewDistilled: "浏览器预览：模拟炼化完成。",
    turningToPoem: (title: string) => `正在翻到《${title}》…`,
    poemFaceUp: (title: string) => `《${title}》已翻到正面。`,
    reviewDefaultPrompt: "请点评这首诗。",
    previewReply: (author: string) => `【浏览器预览模式】\n这是 ${author} 的模拟回应。在桌面端配置 llm.config.json 后，即可与诗人的数字分身真正交谈。`,
    previewCritic: (critic: string) => `【浏览器预览模式】\n这是 ${critic} 的模拟点评。在桌面端配置 llm.config.json 后即可使用真正的评论家模式。`,
    bridgeMissingPrefix: "【桥接未加载】",
    distillFailedPrefix: "【炼化失败】",
    askAuthorIntro: (author: string, meta: string, title: string) => `我是 ${author}，${meta}。你正在读我的《${title}》，有何感想？`,
    feynmanIntro: (title: string) => `我是费曼。让我用最简单的语言，帮你读懂《${title}》。你想从哪里开始？`,
    mungerIntro: (title: string) => `我是芒格。让我用多元思维模型来点评《${title}》。直接点击发送即可开始。`,
  };
};
