import type { PoemRecord } from "./types";

export const poems: PoemRecord[] = [
  {
    id: "jing-ye-si",
    title: "静夜思",
    author: "李白",
    authorMeta: "唐",
    originalLanguage: "zh",
    originalText: ["床前明月光，", "疑是地上霜。", "举头望明月，", "低头思故乡。"],
    translatedTitle: "Quiet Night Thoughts",
    translatedText: [
      "Moonlight spills before my bed,",
      "As if pale frost were on the floor.",
      "I lift my eyes to the bright moon,",
      "Then lower them and miss my home.",
    ],
    translatorNote: "A homesick nocturne built on extreme simplicity and luminous stillness.",
    imagePrompt: "silver moonlight over a quiet wooden room, frost-like glow on dark floorboards, homesick atmosphere, poetic stillness, cinematic realism",
    searchKeywords: ["moonlit room", "homesick night", "poetic moonlight", "Chinese poetry"],
    motionPreset: "cinematic",
  },
  {
    id: "lu-zhai",
    title: "鹿柴",
    author: "王维",
    authorMeta: "唐",
    originalLanguage: "zh",
    originalText: ["空山不见人，", "但闻人语响。", "返景入深林，", "复照青苔上。"],
    translatedTitle: "Deer Enclosure",
    translatedText: [
      "No one is seen in the empty hills,",
      "Only the echo of voices is heard.",
      "Returning light enters the deep woods,",
      "And shines again upon green moss.",
    ],
    translatorNote: "Wang Wei turns absence, echo, and slant light into a complete landscape.",
    imagePrompt: "deep forest with slanting evening sun, emerald moss, invisible figures implied by distant echoes, serene Chinese landscape photography",
    searchKeywords: ["deep forest light", "moss sunlight", "quiet mountain woods"],
    motionPreset: "gallery",
  },
  {
    id: "chun-xiao",
    title: "春晓",
    author: "孟浩然",
    authorMeta: "唐",
    originalLanguage: "zh",
    originalText: ["春眠不觉晓，", "处处闻啼鸟。", "夜来风雨声，", "花落知多少。"],
    translatedTitle: "Spring Dawn",
    translatedText: [
      "I slept in spring and missed the dawn,",
      "Birdsong was everywhere around me.",
      "Last night came wind and rain together,",
      "How many blossoms must have fallen?",
    ],
    translatorNote: "A gentle waking poem where sound reveals the world before sight does.",
    imagePrompt: "spring dawn courtyard after rain, petals on stone, soft birdsong atmosphere, pale light, painterly realism",
    searchKeywords: ["spring dawn rain petals", "birds after rain", "poetry blossom courtyard"],
    motionPreset: "editorial",
  },
  {
    id: "deng-guan-que-lou",
    title: "登鹳雀楼",
    author: "王之涣",
    authorMeta: "唐",
    originalLanguage: "zh",
    originalText: ["白日依山尽，", "黄河入海流。", "欲穷千里目，", "更上一层楼。"],
    translatedTitle: "On the Stork Tower",
    translatedText: [
      "The white sun leans into the mountains,",
      "The Yellow River pours toward the sea.",
      "If you would exhaust a thousand miles of sight,",
      "Climb one more story upward.",
    ],
    translatorNote: "Scale, momentum, and ambition compressed into four lines.",
    imagePrompt: "tower overlooking river at sunset, vast yellow river flowing to sea, heroic horizon, crisp monumental composition",
    searchKeywords: ["river tower sunset", "epic horizon tower", "yellow river landscape"],
    motionPreset: "cinematic",
  },
  {
    id: "yin-hu-shang",
    title: "饮湖上初晴后雨",
    author: "苏轼",
    authorMeta: "宋",
    originalLanguage: "zh",
    originalText: ["水光潋滟晴方好，", "山色空蒙雨亦奇。", "欲把西湖比西子，", "淡妆浓抹总相宜。"],
    translatedTitle: "West Lake: Fair Then Rain",
    translatedText: [
      "On sunny water the lake light ripples in beauty,",
      "In mist and rain the hills are strange and fine.",
      "If West Lake were compared to Xi Shi,",
      "Light makeup or deep adornment, both would suit her.",
    ],
    translatorNote: "Su Shi makes weather itself a cosmetic art.",
    imagePrompt: "West Lake after rain and sunlight, misty hills, elegant water ripples, refined Chinese poetic scenery, graceful feminine metaphor",
    searchKeywords: ["West Lake mist sunlight", "lake after rain", "Chinese poetic lake"],
    motionPreset: "gallery",
  },
  {
    id: "ti-xi-lin-bi",
    title: "题西林壁",
    author: "苏轼",
    authorMeta: "宋",
    originalLanguage: "zh",
    originalText: ["横看成岭侧成峰，", "远近高低各不同。", "不识庐山真面目，", "只缘身在此山中。"],
    translatedTitle: "Written on the Wall at West Forest Temple",
    translatedText: [
      "From the front it forms a ridge, from the side a peak;",
      "Far or near, high or low, each view differs.",
      "I cannot know Mount Lu's true face,",
      "Because I myself am inside the mountain.",
    ],
    translatorNote: "Perspective becomes philosophy in one sudden turn.",
    imagePrompt: "mountain ridges changing shape from different angles, layered mist, philosophical landscape, subtle motion in clouds",
    searchKeywords: ["mountain perspective mist", "ridge and peak", "philosophical landscape"],
    motionPreset: "editorial",
  },
  {
    id: "hope-is-the-thing",
    title: "Hope is the thing with feathers",
    author: "Emily Dickinson",
    authorMeta: "United States",
    originalLanguage: "en",
    originalText: [
      "Hope is the thing with feathers",
      "That perches in the soul,",
      "And sings the tune without the words,",
      "And never stops at all,",
    ],
    translatedTitle: "希望是一只栖在灵魂里的鸟",
    translatedText: [
      "希望，是那只有羽毛的东西，",
      "栖息在人的灵魂里面，",
      "唱着没有词句的曲调，",
      "而且从不曾停歇。",
    ],
    translatorNote: "Dickinson makes hope audible before she makes it visible.",
    imagePrompt: "small bird silhouette glowing inside translucent chest light, poetic minimalism, gentle wind, hopeful atmosphere, editorial art",
    searchKeywords: ["bird hope minimal", "feathers soul art", "poetic hopeful bird"],
    motionPreset: "editorial",
  },
  {
    id: "sonnet-18",
    title: "Sonnet 18",
    author: "William Shakespeare",
    authorMeta: "England",
    originalLanguage: "en",
    originalText: [
      "Shall I compare thee to a summer's day?",
      "Thou art more lovely and more temperate:",
      "Rough winds do shake the darling buds of May,",
      "And summer's lease hath all too short a date;",
    ],
    translatedTitle: "十四行诗十八首",
    translatedText: [
      "我怎能把你比作夏天的一日？",
      "你比夏天更可爱，也更温柔：",
      "五月娇蕾会被狂风吹得摇曳，",
      "而夏天的租期也未免过于短促；",
    ],
    translatorNote: "The poem's immortality argument begins with a meteorological objection.",
    imagePrompt: "gentle summer garden with wind shaking flower buds, warm golden light, timeless romantic portrait atmosphere, classical elegance",
    searchKeywords: ["summer garden wind buds", "classic romantic light", "Shakespeare summer day"],
    motionPreset: "gallery",
  },
  {
    id: "the-sick-rose",
    title: "The Sick Rose",
    author: "William Blake",
    authorMeta: "England",
    originalLanguage: "en",
    originalText: [
      "O Rose, thou art sick!",
      "The invisible worm,",
      "That flies in the night,",
      "In the howling storm,",
    ],
    translatedTitle: "病玫瑰",
    translatedText: [
      "噢，玫瑰，你病了！",
      "那条看不见的虫，",
      "在夜里飞来，",
      "伴着呼啸的风暴，",
    ],
    translatorNote: "A miniature gothic vision with the force of an omen.",
    imagePrompt: "single crimson rose in storm at night, invisible menace implied, gothic darkness, dramatic wind, high contrast art direction",
    searchKeywords: ["rose storm night gothic", "dark flower poetry", "crimson rose wind"],
    motionPreset: "cinematic",
  },
  {
    id: "bright-star",
    title: "Bright Star",
    author: "John Keats",
    authorMeta: "England",
    originalLanguage: "en",
    originalText: [
      "Bright star! would I were steadfast as thou art—",
      "Not in lone splendour hung aloft the night,",
      "And watching, with eternal lids apart,",
      "Like nature's patient, sleepless Eremite,",
    ],
    translatedTitle: "明亮的星",
    translatedText: [
      "明亮的星啊！我愿如你一般坚定——",
      "却不是孤悬夜空、独自辉耀，",
      "不是永远睁着眼睛守望，",
      "像大自然里耐心而不眠的隐修者，",
    ],
    translatorNote: "Keats longs for permanence but refuses loneliness.",
    imagePrompt: "single bright star above sleeping sea, patient night sky, romantic stillness, soft cloud drift, luminous poetic scene",
    searchKeywords: ["bright star night sea", "romantic night sky", "poetic horizon star"],
    motionPreset: "cinematic",
  },
  {
    id: "daffodils",
    title: "I Wandered Lonely as a Cloud",
    author: "William Wordsworth",
    authorMeta: "England",
    originalLanguage: "en",
    originalText: [
      "I wandered lonely as a cloud",
      "That floats on high o'er vales and hills,",
      "When all at once I saw a crowd,",
      "A host, of golden daffodils;",
    ],
    translatedTitle: "我孤独地漫游，像一朵云",
    translatedText: [
      "我孤独地漫游，像一朵云，",
      "高高飘过山谷与群山；",
      "忽然间，我望见一大片，",
      "一大片金黄的水仙花；",
    ],
    translatorNote: "Solitude turns into abundance in a single glance.",
    imagePrompt: "golden daffodil field under drifting clouds, light breeze, luminous spring landscape, expansive romantic composition",
    searchKeywords: ["golden daffodils field", "cloud over hills poetry", "romantic spring flowers"],
    motionPreset: "gallery",
  },
  {
    id: "cloths-of-heaven",
    title: "He Wishes for the Cloths of Heaven",
    author: "W. B. Yeats",
    authorMeta: "Ireland",
    originalLanguage: "en",
    originalText: [
      "Had I the heavens' embroidered cloths,",
      "Enwrought with golden and silver light,",
      "The blue and the dim and the dark cloths",
      "Of night and light and the half-light,",
    ],
    translatedTitle: "他愿拥有天国的织锦",
    translatedText: [
      "倘若我拥有天国绣成的织锦，",
      "织满金色与银色的光辉，",
      "拥有蓝色、幽暗与漆黑的布匹，",
      "那些夜色、光亮与半明半暗的织物，",
    ],
    translatorNote: "Yeats turns the sky into a gift too delicate to spend.",
    imagePrompt: "embroidered night sky cloth with gold and silver light, deep blue velvet atmosphere, luxurious but delicate poetic textile imagery",
    searchKeywords: ["embroidered sky cloth", "gold silver night textile", "poetic heaven fabric"],
    motionPreset: "editorial",
  },
];

export const poemIndex = new Map(poems.map((poem) => [poem.id, poem]));
